on:
  push:
    branches: [main]

jobs: 
  delpoy: 
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
          go-version: "1.23.0"
        
    - name: Build app
      uses: ./scripts/buildprod.sh